export interface FontEntry {
  displayName: string
  variants: string[]
  projectFonts: string[]
  stylesCount: number
  source: string
  cssFamily: string
  weightMap: Record<string, string>
}

export const FONT_INVENTORY: Record<string, FontEntry> = {
  'helvetica-now-mt-text': {
    displayName: 'Helvetica Now MT Text',
    variants: ['Thin', 'XtraLt', 'Light', 'Regular', 'Medium', 'Bold', 'XtraBd', 'Black'],
    projectFonts: ['Regular', 'Medium', 'Bold'],
    stylesCount: 18,
    source: 'Monotype',
    cssFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    weightMap: { Thin: '100', XtraLt: '200', Light: '300', Regular: '400', Medium: '500', Bold: '700', XtraBd: '800', Black: '900' },
  },
  'helvetica-now-mt-display': {
    displayName: 'Helvetica Now MT Display',
    variants: ['Hair', 'Thin', 'XtraLt', 'Light', 'Regular', 'Medium', 'Bold', 'XtraBd', 'XBlk', 'Black'],
    projectFonts: ['Regular', 'Bold'],
    stylesCount: 20,
    source: 'Monotype',
    cssFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    weightMap: { Hair: '100', Thin: '200', XtraLt: '200', Light: '300', Regular: '400', Medium: '500', Bold: '700', XtraBd: '800', XBlk: '900', Black: '900' },
  },
  'avenir': {
    displayName: 'Avenir',
    variants: ['Light', 'Book', 'Roman', 'Medium', 'Heavy', 'Black'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Monotype',
    cssFamily: "Avenir, 'Gill Sans', sans-serif",
    weightMap: { Light: '300', Book: '400', Roman: '400', Medium: '500', Heavy: '700', Black: '900' },
  },
  'avenir-next': {
    displayName: 'Avenir Next',
    variants: ['UltraLight', 'Regular', 'Medium', 'DemiBold', 'Bold', 'Heavy'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Monotype',
    cssFamily: "'Avenir Next', Avenir, sans-serif",
    weightMap: { UltraLight: '200', Regular: '400', Medium: '500', DemiBold: '600', Bold: '700', Heavy: '800' },
  },
  'helvetica-neue': {
    displayName: 'Helvetica Neue',
    variants: ['25 UltraLight', '35 Thin', '45 Light', '55 Roman', '65 Medium', '75 Bold', '85 Heavy', '95 Black'],
    projectFonts: [],
    stylesCount: 16,
    source: 'Monotype',
    cssFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    weightMap: { '25 UltraLight': '100', '35 Thin': '200', '45 Light': '300', '55 Roman': '400', '65 Medium': '500', '75 Bold': '700', '85 Heavy': '800', '95 Black': '900' },
  },
  'futura': {
    displayName: 'Futura',
    variants: ['Light', 'Book', 'Medium', 'DemiBold', 'Bold', 'ExtraBold'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Monotype',
    cssFamily: "Futura, 'Futura PT', sans-serif",
    weightMap: { Light: '300', Book: '400', Medium: '500', DemiBold: '600', Bold: '700', ExtraBold: '800' },
  },
  'gill-sans': {
    displayName: 'Gill Sans',
    variants: ['Light', 'Regular', 'Medium', 'SemiBold', 'Bold', 'Heavy', 'Ultra Bold'],
    projectFonts: [],
    stylesCount: 14,
    source: 'Monotype',
    cssFamily: "'Gill Sans', 'Gill Sans MT', sans-serif",
    weightMap: { Light: '300', Regular: '400', Medium: '500', SemiBold: '600', Bold: '700', Heavy: '800', 'Ultra Bold': '900' },
  },
  'gotham': {
    displayName: 'Gotham',
    variants: ['Thin', 'XLight', 'Light', 'Book', 'Medium', 'Bold', 'Black', 'Ultra'],
    projectFonts: [],
    stylesCount: 16,
    source: 'Monotype',
    cssFamily: "Gotham, 'Gotham SSm', sans-serif",
    weightMap: { Thin: '100', XLight: '200', Light: '300', Book: '400', Medium: '500', Bold: '700', Black: '900', Ultra: '900' },
  },
  'trade-gothic': {
    displayName: 'Trade Gothic',
    variants: ['Light', 'Regular', 'Bold', 'Bold No. 2', 'Condensed', 'Extended'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Monotype',
    cssFamily: "'Trade Gothic', 'Trade Gothic LT', sans-serif",
    weightMap: { Light: '300', Regular: '400', Bold: '700', 'Bold No. 2': '800', Condensed: '400', Extended: '400' },
  },
  'din-next': {
    displayName: 'DIN Next',
    variants: ['UltraLight', 'Light', 'Regular', 'Medium', 'Bold', 'Heavy', 'Black'],
    projectFonts: [],
    stylesCount: 14,
    source: 'Monotype',
    cssFamily: "'DIN Next', DIN, sans-serif",
    weightMap: { UltraLight: '200', Light: '300', Regular: '400', Medium: '500', Bold: '700', Heavy: '800', Black: '900' },
  },
  'proxima-nova': {
    displayName: 'Proxima Nova',
    variants: ['Thin', 'Light', 'Regular', 'Semibold', 'Bold', 'Extrabold', 'Black'],
    projectFonts: [],
    stylesCount: 14,
    source: 'Monotype',
    cssFamily: "'Proxima Nova', sans-serif",
    weightMap: { Thin: '100', Light: '300', Regular: '400', Semibold: '600', Bold: '700', Extrabold: '800', Black: '900' },
  },
  'neue-haas-grotesk': {
    displayName: 'Neue Haas Grotesk',
    variants: ['Thin', 'Light', 'Roman', 'Medium', 'Bold', 'Black'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Monotype',
    cssFamily: "'Neue Haas Grotesk', Helvetica, sans-serif",
    weightMap: { Thin: '200', Light: '300', Roman: '400', Medium: '500', Bold: '700', Black: '900' },
  },
  'univers': {
    displayName: 'Univers',
    variants: ['Light', 'Roman', 'Bold', 'Black', 'Condensed', 'Extended'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Monotype',
    cssFamily: "Univers, 'Univers LT', sans-serif",
    weightMap: { Light: '300', Roman: '400', Bold: '700', Black: '900', Condensed: '400', Extended: '400' },
  },
  'frutiger': {
    displayName: 'Frutiger',
    variants: ['Light', 'Roman', 'Bold', 'Black', 'Ultra Black'],
    projectFonts: [],
    stylesCount: 10,
    source: 'Monotype',
    cssFamily: "Frutiger, 'Frutiger LT', sans-serif",
    weightMap: { Light: '300', Roman: '400', Bold: '700', Black: '900', 'Ultra Black': '900' },
  },
  'myriad-set': {
    displayName: 'Myriad Set',
    variants: ['Thin', 'Light', 'Regular', 'Semibold', 'Bold'],
    projectFonts: [],
    stylesCount: 10,
    source: 'Monotype',
    cssFamily: "'Myriad Set', 'Myriad Pro', sans-serif",
    weightMap: { Thin: '200', Light: '300', Regular: '400', Semibold: '600', Bold: '700' },
  },
  'garamond-premier': {
    displayName: 'Garamond Premier',
    variants: ['Regular', 'Medium', 'Semibold', 'Bold'],
    projectFonts: [],
    stylesCount: 8,
    source: 'Monotype',
    cssFamily: "'Garamond Premier', Garamond, serif",
    weightMap: { Regular: '400', Medium: '500', Semibold: '600', Bold: '700' },
  },
  'sabon': {
    displayName: 'Sabon',
    variants: ['Roman', 'Bold'],
    projectFonts: [],
    stylesCount: 4,
    source: 'Monotype',
    cssFamily: "Sabon, 'Sabon LT', serif",
    weightMap: { Roman: '400', Bold: '700' },
  },
  'georgia': {
    displayName: 'Georgia',
    variants: ['Regular', 'Bold'],
    projectFonts: [],
    stylesCount: 4,
    source: 'System',
    cssFamily: "Georgia, 'Times New Roman', serif",
    weightMap: { Regular: '400', Bold: '700' },
  },
  'roboto': {
    displayName: 'Roboto',
    variants: ['Thin', 'Light', 'Regular', 'Medium', 'Bold', 'Black'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Google / Monotype',
    cssFamily: "Roboto, 'Helvetica Neue', sans-serif",
    weightMap: { Thin: '100', Light: '300', Regular: '400', Medium: '500', Bold: '700', Black: '900' },
  },
  'inter': {
    displayName: 'Inter',
    variants: ['Thin', 'ExtraLight', 'Light', 'Regular', 'Medium', 'SemiBold', 'Bold', 'ExtraBold', 'Black'],
    projectFonts: [],
    stylesCount: 18,
    source: 'Google / Monotype',
    cssFamily: "Inter, 'Helvetica Neue', sans-serif",
    weightMap: { Thin: '100', ExtraLight: '200', Light: '300', Regular: '400', Medium: '500', SemiBold: '600', Bold: '700', ExtraBold: '800', Black: '900' },
  },
  'open-sans': {
    displayName: 'Open Sans',
    variants: ['Light', 'Regular', 'Medium', 'SemiBold', 'Bold', 'ExtraBold'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Google / Monotype',
    cssFamily: "'Open Sans', 'Helvetica Neue', sans-serif",
    weightMap: { Light: '300', Regular: '400', Medium: '500', SemiBold: '600', Bold: '700', ExtraBold: '800' },
  },
  'montserrat': {
    displayName: 'Montserrat',
    variants: ['Thin', 'Light', 'Regular', 'Medium', 'SemiBold', 'Bold', 'ExtraBold', 'Black'],
    projectFonts: [],
    stylesCount: 16,
    source: 'Google / Monotype',
    cssFamily: "Montserrat, 'Helvetica Neue', sans-serif",
    weightMap: { Thin: '100', Light: '300', Regular: '400', Medium: '500', SemiBold: '600', Bold: '700', ExtraBold: '800', Black: '900' },
  },
  'poppins': {
    displayName: 'Poppins',
    variants: ['Thin', 'ExtraLight', 'Light', 'Regular', 'Medium', 'SemiBold', 'Bold', 'ExtraBold', 'Black'],
    projectFonts: [],
    stylesCount: 18,
    source: 'Google / Monotype',
    cssFamily: "Poppins, sans-serif",
    weightMap: { Thin: '100', ExtraLight: '200', Light: '300', Regular: '400', Medium: '500', SemiBold: '600', Bold: '700', ExtraBold: '800', Black: '900' },
  },
  'lato': {
    displayName: 'Lato',
    variants: ['Hairline', 'Thin', 'Light', 'Regular', 'Medium', 'Semibold', 'Bold', 'Heavy', 'Black'],
    projectFonts: [],
    stylesCount: 18,
    source: 'Google / Monotype',
    cssFamily: "Lato, 'Helvetica Neue', sans-serif",
    weightMap: { Hairline: '100', Thin: '200', Light: '300', Regular: '400', Medium: '500', Semibold: '600', Bold: '700', Heavy: '800', Black: '900' },
  },
  'source-sans-pro': {
    displayName: 'Source Sans Pro',
    variants: ['ExtraLight', 'Light', 'Regular', 'SemiBold', 'Bold', 'Black'],
    projectFonts: [],
    stylesCount: 12,
    source: 'Google / Monotype',
    cssFamily: "'Source Sans Pro', 'Helvetica Neue', sans-serif",
    weightMap: { ExtraLight: '200', Light: '300', Regular: '400', SemiBold: '600', Bold: '700', Black: '900' },
  },
  'bebas-neue': {
    displayName: 'Bebas Neue',
    variants: ['Thin', 'Light', 'Regular', 'Bold'],
    projectFonts: [],
    stylesCount: 4,
    source: 'Monotype',
    cssFamily: "'Bebas Neue', Impact, sans-serif",
    weightMap: { Thin: '200', Light: '300', Regular: '400', Bold: '700' },
  },
  'minion-pro': {
    displayName: 'Minion Pro',
    variants: ['Regular', 'Medium', 'Semibold', 'Bold'],
    projectFonts: [],
    stylesCount: 8,
    source: 'Monotype',
    cssFamily: "'Minion Pro', Minion, serif",
    weightMap: { Regular: '400', Medium: '500', Semibold: '600', Bold: '700' },
  },
  'speedee': {
    displayName: 'Speedee',
    variants: ['Light', 'Regular', 'Bold', 'Condensed'],
    projectFonts: [],
    stylesCount: 8,
    source: 'Monotype',
    cssFamily: "Speedee, Arial, sans-serif",
    weightMap: { Light: '300', Regular: '400', Bold: '700', Condensed: '400' },
  },
  'aktiv-grotesk': {
    displayName: 'Aktiv Grotesk',
    variants: ['Hair', 'Thin', 'Light', 'Regular', 'Medium', 'Bold', 'XBold', 'Black'],
    projectFonts: [],
    stylesCount: 16,
    source: 'Monotype',
    cssFamily: "'Aktiv Grotesk', 'Helvetica Neue', sans-serif",
    weightMap: { Hair: '100', Thin: '200', Light: '300', Regular: '400', Medium: '500', Bold: '700', XBold: '800', Black: '900' },
  },
  'noto-sans': {
    displayName: 'Noto Sans',
    variants: ['Thin', 'Light', 'Regular', 'Medium', 'SemiBold', 'Bold', 'ExtraBold', 'Black'],
    projectFonts: [],
    stylesCount: 16,
    source: 'Google / Monotype',
    cssFamily: "'Noto Sans', sans-serif",
    weightMap: { Thin: '100', Light: '300', Regular: '400', Medium: '500', SemiBold: '600', Bold: '700', ExtraBold: '800', Black: '900' },
  },
}
